/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TorrentsRouteImport } from './routes/_torrents'
import { Route as ConnectRouteImport } from './routes/connect'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as TorrentsIndexRouteImport } from './routes/_torrents/index'
import { Route as TorrentsTorrentsTorrentIdRouteImport } from './routes/_torrents/torrents.$torrentId'

const TorrentsRoute = TorrentsRouteImport.update({
  id: '/_torrents',
  getParentRoute: () => rootRouteImport,
} as any)
const ConnectRoute = ConnectRouteImport.update({
  id: '/connect',
  path: '/connect',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const TorrentsIndexRoute = TorrentsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => TorrentsRoute,
} as any)
const TorrentsTorrentsTorrentIdRoute =
  TorrentsTorrentsTorrentIdRouteImport.update({
    id: '/torrents/$torrentId',
    path: '/torrents/$torrentId',
    getParentRoute: () => TorrentsRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof TorrentsIndexRoute
  '/connect': typeof ConnectRoute
  '/settings': typeof SettingsRoute
  '/torrents/$torrentId': typeof TorrentsTorrentsTorrentIdRoute
}
export interface FileRoutesByTo {
  '/connect': typeof ConnectRoute
  '/settings': typeof SettingsRoute
  '/': typeof TorrentsIndexRoute
  '/torrents/$torrentId': typeof TorrentsTorrentsTorrentIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_torrents': typeof TorrentsRouteWithChildren
  '/connect': typeof ConnectRoute
  '/settings': typeof SettingsRoute
  '/_torrents/': typeof TorrentsIndexRoute
  '/_torrents/torrents/$torrentId': typeof TorrentsTorrentsTorrentIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/connect' | '/settings' | '/torrents/$torrentId'
  fileRoutesByTo: FileRoutesByTo
  to: '/connect' | '/settings' | '/' | '/torrents/$torrentId'
  id:
    | '__root__'
    | '/_torrents'
    | '/connect'
    | '/settings'
    | '/_torrents/'
    | '/_torrents/torrents/$torrentId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  TorrentsRoute: typeof TorrentsRouteWithChildren
  ConnectRoute: typeof ConnectRoute
  SettingsRoute: typeof SettingsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_torrents': {
      id: '/_torrents'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof TorrentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/connect': {
      id: '/connect'
      path: '/connect'
      fullPath: '/connect'
      preLoaderRoute: typeof ConnectRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_torrents/': {
      id: '/_torrents/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof TorrentsIndexRouteImport
      parentRoute: typeof TorrentsRoute
    }
    '/_torrents/torrents/$torrentId': {
      id: '/_torrents/torrents/$torrentId'
      path: '/torrents/$torrentId'
      fullPath: '/torrents/$torrentId'
      preLoaderRoute: typeof TorrentsTorrentsTorrentIdRouteImport
      parentRoute: typeof TorrentsRoute
    }
  }
}

interface TorrentsRouteChildren {
  TorrentsIndexRoute: typeof TorrentsIndexRoute
  TorrentsTorrentsTorrentIdRoute: typeof TorrentsTorrentsTorrentIdRoute
}

const TorrentsRouteChildren: TorrentsRouteChildren = {
  TorrentsIndexRoute: TorrentsIndexRoute,
  TorrentsTorrentsTorrentIdRoute: TorrentsTorrentsTorrentIdRoute,
}

const TorrentsRouteWithChildren = TorrentsRoute._addFileChildren(
  TorrentsRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  TorrentsRoute: TorrentsRouteWithChildren,
  ConnectRoute: ConnectRoute,
  SettingsRoute: SettingsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
